name: epyfilter
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiofiles=22.1.0=py311h06a4308_0
  - aiosqlite=0.18.0=py311h06a4308_0
  - ansi2html=1.9.1=py311h06a4308_0
  - anyio=3.5.0=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py311h06a4308_0
  - babel=2.11.0=py311h06a4308_0
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - dash=2.14.2=py311h06a4308_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - flask=2.2.5=py311h06a4308_0
  - flask-compress=1.13=py311h06a4308_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipython=8.20.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.3=py311h06a4308_0
  - joblib=1.2.0=py311h06a4308_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter-dash=0.4.2=py311h06a4308_0
  - jupyter_client=7.4.9=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - jupyter_events=0.8.0=py311h06a4308_0
  - jupyter_server=1.23.4=py311h06a4308_0
  - jupyter_server_fileid=0.9.0=py311h06a4308_0
  - jupyter_server_ydoc=0.8.0=py311h06a4308_1
  - jupyter_ydoc=0.2.4=py311h06a4308_0
  - jupyterlab=3.6.3=py311h06a4308_0
  - jupyterlab_pygments=0.2.2=py311h06a4308_0
  - jupyterlab_server=2.25.1=py311h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - nbclassic=1.0.0=py311h06a4308_0
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.10.0=py311h06a4308_0
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - notebook=6.5.4=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openssl=3.0.15=h5eee18b_0
  - pandas=2.1.1=py311ha02d727_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - plotly=5.9.0=py311h06a4308_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=23.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - requests=2.31.0=py311h06a4308_1
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py311h06a4308_0
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.7.1=py311h06a4308_0
  - typing-extensions=4.9.0=py311h06a4308_1
  - typing_extensions=4.9.0=py311h06a4308_1
  - tzdata=2023d=h04d1e81_0
  - urllib3=2.1.0=py311h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - werkzeug=2.3.8=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - y-py=0.5.9=py311h52d8a92_0
  - yaml=0.2.5=h7b6447c_0
  - ypy-websocket=0.8.2=py311h06a4308_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.43.1
      - gitdb==4.0.11
      - gitpython==3.1.41
      - ipywidgets==8.1.2
      - joypy==0.2.6
      - jupyter-server-mathjax==0.2.6
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - nbdime==4.0.1
      - networkx==3.2.1
      - packaging==23.2
      - pillow==10.1.0
      - pyparsing==3.1.1
      - pypdf==3.17.0
      - pywavelets==1.4.1
      - scipy==1.11.3
      - seaborn==0.13.2
      - smmap==5.0.1
      - widgetsnbextension==4.0.10
prefix: /ifs/scratch/jls106_gp/nhw2114/anaconda3/envs/epyfilter
